# Generated by Django 2.2.5 on 2020-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0017_auto_20200130_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='centsite',
            field=models.CharField(blank=True, help_text='Observatory Site Code', max_length=50, null=True, verbose_name='Centre-Site Name'),
        ),
        migrations.AddField(
            model_name='target',
            name='eph_json',
            field=models.TextField(blank=True, help_text="Don't fill this in by hand unless you know what you are doing.", null=True, verbose_name='Ephemeris JSON'),
        ),
        migrations.AlterField(
            model_name='target',
            name='scheme',
            field=models.CharField(blank=True, choices=[('MPC_MINOR_PLANET', 'MPC Minor Planet'), ('MPC_COMET', 'MPC Comet'), ('JPL_MAJOR_PLANET', 'JPL Major Planet'), ('EPHEMERIS', 'Custom Ephemeris')], default='', max_length=50, verbose_name='Orbital Element Scheme'),
        ),
    ]
